### ISSUE TITLE
project 1] 뭘 해야 할지?

### ISSUE THREAD

**Issue by 1more** [ddaddabae/pintosStudy#1]
프로젝트 1에서 해야하는 것 확인
[참고(공식영어문서)](https://web.stanford.edu/class/cs140/projects/pintos/pintos_14.html#SEC172)
[참고(한글문서)](http://maplejune.tistory.com/entry/Pintos-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-1-Priority-Scheduling)
- 뭘 구현해야 하는지
- 어떻게 테스트 하는지
- thread 학습

방법 알게되는 대로 댓글 부탁해요!

**Comment by 1more** [comment]
@JeoKim224 
진척을 시키거라

**Comment by JeoKim224** [comment]
넵충성!

**Comment by 1more** [comment]
- 학습

부분은 [여기](https://web.stanford.edu/class/cs140/projects/pintos/pintos_6.html#SEC91)에 나와있네. 영어라 힘들지만....

**Comment by JeoKim224** [comment]
내일은 틈틈이 이거 읽어봐야겠당ㅋㅋ 영어라 딴짓하는 줄 모를것같은 긍정적인 예감 ㅋㅋㅋ

**Comment by Ms-cookie** [comment]
ㅋㅋ 번역기 돌리고 싶당..... 넘나 긴것..

**Comment by JeoKim224** [comment]
웩 나 뭔가 오늘 영어문서 읽기 실패....ㅠㅠㅠㅠㅠ

**Comment by Ms-cookie** [comment]
우리 다음번까지 뭐한다고 했드랑??? 콛잉해보기?

**Comment by 1more** [comment]
@Ms-cookie 응코딩해보기.... 나 내일 해커톤나가는데.... 가능할까...ㅋㅋㅋ
